### PR TITLE
GL renderer

### PR DESCRIPTION
**Pull request by codeandkey**
needs a little bit of work -- doesn't look like obj_example scales the texture correctly (which is weird because all the other textures work fine)

gl
sdl

There are clear problems with scaling on both the light and example objects.
obj_fog and obj_bg were removed because porting them was painful and I don't think we'll use them much in the future.

@quigley-c do things work? GL functions are loaded manually so no glxw this time

### CODE REVIEW

**Comment by quigley-c** [comment]
Everything seems to work as you have described. Backgrounds and fog go a long way to making everything look good, so losing them is a shame. 

@molecuul including my own screenshots for reference:
gl
sdl

**Comment by quigley-c** [comment]
Not sure if a merge at the moment is the best idea. Thoughts?

**Comment by codeandkey** [comment]
I agree, too unstable for merging now but hopefully soon. Replacements will come for the background and fog effects but they will be more tailored to the new graphics model -- the current ones are very dependent on camera and display sizes and don't change very well

If this takes too long a rewrite of the current SDL backend is in order to match the new opt-based model which shouldn't be too bad; this will save a bunch of work in the future allowing easy swapping of backends (perhaps even supporting both to let users without GPUs play)

**Comment by codeandkey** [comment]
There's also a patch to the event subsystem memory model within this branch that fixes certain unsubscribing patterns from crashing the game

**Comment by codeandkey** [comment]
This looks good to go, merging

**Pull request merged**
